namespace               = "weather-station-staging"
backend_image_tag       = "development"
socket_server_image_tag = "edge"
web_ui_image_tag        = "edge"
database_size_limit     = "8Gi"
environment_root_folder = "/mnt/kubernetes/weather-station/staging"