name: on-dispatch-destroy
concurrency:
  group: on-dispatch-destroy
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      env-name:
        description: Environment name (staging or production)
        type: string
        required: true
jobs:
  destroy-infrastructure:
    uses: davidleonm/cicd-pipelines/.github/workflows/deploy-infrastructure.yml@master
    with:
      terraform-version: ~1.10.0
      env-name: ${{ inputs.env-name }}
      destroy-environment: true
    secrets:
      kubernetes-config-base64: ${{ secrets.KUBERNETES_CONFIG_BASE64 }}
      vars-list: "TF_VAR_database_admin_password=${{ secrets.DB_ADMIN_PASSWORD }}"